### ISSUE TITLE
Duplicate option when registering for a course

### ISSUE THREAD

**Issue by alastairrailton** [yalla-coop/public-QA-repo#3]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Microsoft Edge

### What kind of issue is it?

Copy

### Priority

Medium

### User Type

Logged in Participant

### Please describe your issue & include screenshots:

When registering for a course, two repeated boxes appear saying the same thing
![Picture1](https://github.com/user-attachments/assets/c7f6ea5c-f41c-4bc4-a748-e2ec15d8e926)

### Page URL

ICS Training (nhct-c5-staging.herokuapp.com)

**Comment by egasparini** [comment]
@alastairrailton thanks for reporting this.
We still need to update the survey functionality, it's a bit messy at the moment. This will all be working as expected after the current sprint.
