### ISSUE TITLE
No programmes listed for programme manager

### ISSUE THREAD

**Issue by alastairrailton** [yalla-coop/public-QA-repo#6]
### Device

Windows Laptop

### What browsers are you seeing the problem on?

Microsoft Edge

### What kind of issue is it?

Bug

### Priority

High

### User Type

Logged in Programme Manager

### Please describe your issue & include screenshots:

There is no option to manage any of the programmes
![image](https://github.com/user-attachments/assets/bd25f269-1bc0-4ee2-beed-10e9fa49a9f4)

### Page URL

https://nhct-c5-staging.herokuapp.com/manage/programmes/select

**Comment by egasparini** [comment]
Thanks for reporting this @alastairrailton.
I have grouped this with the other issue you reported and we will address them together. I will close this in the meanwhile.
